server:
  port: 8081
spring:
  application:
    name: user-center
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ningli?useUnicode=true&characterEncoding=utf-8&mysqlEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/